// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace InvestmentBankingAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Adjustment")]
    public partial class AdjustmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Adjustment.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Adjustment", "-Adjustment search\r\n-add Adjustment", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
testRunner.Given("Smith has launched the intrepid application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserNameField",
                        "PasswordField"});
            table1.AddRow(new string[] {
                        "NewUserTest",
                        "P@ssword12"});
#line 7
 testRunner.And("Smith entered the following login details", ((string)(null)), table1, "And ");
#line hidden
#line 11
 testRunner.And("Smith clicked login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And("smith clicked on the Adjustment Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by entering All fields")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchAdjustmentByEnteringAllFields()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by entering All fields", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table2.AddRow(new string[] {
                            "Dynamic",
                            "11/23/2023",
                            "06/01/2026",
                            "Andersen, Autumn",
                            "GRID"});
#line 16
 testRunner.And("Smith entered the following Search adjustment details", ((string)(null)), table2, "And ");
#line hidden
#line 19
 testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by InvestmentBanker and AdjustmentCode")]
        public void SearchAdjustmentByInvestmentBankerAndAdjustmentCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by InvestmentBanker and AdjustmentCode", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table3.AddRow(new string[] {
                            "",
                            "",
                            "",
                            "Andersen, Autumn",
                            "GRID"});
#line 23
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table3, "Given ");
#line hidden
#line 26
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentCycleDate and InvestmentBanker")]
        public void SearchAdjustmentByAdjustmentCycleDateAndInvestmentBanker()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentCycleDate and InvestmentBanker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table4.AddRow(new string[] {
                            "",
                            "11/23/2023",
                            "06/01/2026",
                            "Andersen, Autumn",
                            ""});
#line 30
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table4, "Given ");
#line hidden
#line 33
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentMode and InvestmentBanker")]
        public void SearchAdjustmentByAdjustmentModeAndInvestmentBanker()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentMode and InvestmentBanker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table5.AddRow(new string[] {
                            "Dynamic",
                            "",
                            "",
                            "Andersen, Autumn",
                            ""});
#line 37
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table5, "Given ");
#line hidden
#line 40
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentMode, AdjustmentCycleDate and InvestmentBanker")]
        public void SearchAdjustmentByAdjustmentModeAdjustmentCycleDateAndInvestmentBanker()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentMode, AdjustmentCycleDate and InvestmentBanker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table6.AddRow(new string[] {
                            "Dynamic",
                            "11/23/2023",
                            "06/01/2026",
                            "Andersen, Autumn",
                            ""});
#line 44
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table6, "Given ");
#line hidden
#line 47
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentCode and AdjustmentCycleDate")]
        public void SearchAdjustmentByAdjustmentCodeAndAdjustmentCycleDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentCode and AdjustmentCycleDate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table7.AddRow(new string[] {
                            "",
                            "05/11/2023",
                            "01/11/2026",
                            "",
                            "GRID"});
#line 52
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table7, "Given ");
#line hidden
#line 55
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentMode, InvestmentBanker and AdjustmentCode")]
        public void SearchAdjustmentByAdjustmentModeInvestmentBankerAndAdjustmentCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentMode, InvestmentBanker and AdjustmentCode", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table8.AddRow(new string[] {
                            "Dynamic",
                            "",
                            "",
                            "Andersen, Autumn",
                            "GRID"});
#line 61
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table8, "Given ");
#line hidden
#line 64
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentCycleDate, InvestmentBanker and AdjustmentCode")]
        public void SearchAdjustmentByAdjustmentCycleDateInvestmentBankerAndAdjustmentCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentCycleDate, InvestmentBanker and AdjustmentCode", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table9.AddRow(new string[] {
                            "",
                            "05/11/2023",
                            "01/11/2026",
                            "Andersen, Autumn",
                            "GRID"});
#line 69
testRunner.Given("Smith entered the following Search adjustment details", ((string)(null)), table9, "Given ");
#line hidden
#line 73
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 74
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment with no filter")]
        public void SearchAdjustmentWithNoFilter()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment with no filter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table10.AddRow(new string[] {
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 79
testRunner.And("Smith entered the following Search adjustment details", ((string)(null)), table10, "And ");
#line hidden
#line 82
testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 83
testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Adjustment by AdjustmentMode and AdjustmentCycleDate")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchAdjustmentByAdjustmentModeAndAdjustmentCycleDate()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Adjustment by AdjustmentMode and AdjustmentCycleDate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode"});
                table11.AddRow(new string[] {
                            "Dynamic",
                            "05/07/2023",
                            "02/28/2026",
                            "",
                            ""});
#line 87
 testRunner.And("Smith entered the following Search adjustment details", ((string)(null)), table11, "And ");
#line hidden
#line 90
 testRunner.When("[Smith clicks Search Adjustment button]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 91
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment add all fields-> setting adjustment mode to Recurring")]
        [NUnit.Framework.CategoryAttribute("Edit")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddAdjustmentAddAllFields_SettingAdjustmentModeToRecurring()
        {
            string[] tagsOfScenario = new string[] {
                    "Edit",
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment add all fields-> setting adjustment mode to Recurring", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 114
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 115
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table12.AddRow(new string[] {
                            "Recurring",
                            "faker_startdate",
                            "faker_enddate",
                            "Andersen, Autumn",
                            "GRID",
                            "faker_amount",
                            "faker_note"});
#line 116
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table12, "And ");
#line hidden
#line 119
 testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 120
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment add all fields-> setting adjustment mode to Dynamic")]
        public void AddAdjustmentAddAllFields_SettingAdjustmentModeToDynamic()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment add all fields-> setting adjustment mode to Dynamic", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 123
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 124
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table13.AddRow(new string[] {
                            "Dynamic",
                            "faker_startdate",
                            "faker_enddate",
                            "Andersen, Autumn",
                            "GRID",
                            "faker_amount",
                            "faker_note"});
#line 125
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table13, "And ");
#line hidden
#line 128
 testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 129
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment add all fields-> setting adjustment mode to One Time")]
        public void AddAdjustmentAddAllFields_SettingAdjustmentModeToOneTime()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment add all fields-> setting adjustment mode to One Time", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 134
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table14.AddRow(new string[] {
                            "Dynamic",
                            "faker_startdate",
                            "faker_enddate",
                            "Andersen, Autumn",
                            "GRID",
                            "faker_amount",
                            "faker_note"});
#line 135
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table14, "And ");
#line hidden
#line 138
 testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 139
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add required fields only on Add adjusttment")]
        public void AddRequiredFieldsOnlyOnAddAdjusttment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add required fields only on Add adjusttment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 141
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 142
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table15.AddRow(new string[] {
                            "Dynamic",
                            "",
                            "",
                            "Andersen, Autumn",
                            "GRID",
                            "",
                            ""});
#line 143
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table15, "And ");
#line hidden
#line 146
 testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 147
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment with missing required fields")]
        public void AddAdjustmentWithMissingRequiredFields()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment with missing required fields", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 149
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 150
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table16.AddRow(new string[] {
                            "",
                            "faker_startdate",
                            "faker_enddate",
                            "",
                            "",
                            "faker_amount",
                            "faker_note"});
#line 151
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table16, "And ");
#line hidden
#line 154
testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 155
testRunner.Then("[Smith should see an error message indicating missing required fields]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment add all required  fields and amount only")]
        public void AddAdjustmentAddAllRequiredFieldsAndAmountOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment add all required  fields and amount only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 158
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 159
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table17.AddRow(new string[] {
                            "Dynamic",
                            "",
                            "",
                            "Andersen, Autumn",
                            "GRID",
                            "faker_amount",
                            ""});
#line 160
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table17, "And ");
#line hidden
#line 163
 testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 164
 testRunner.Then("[Smith should see the search Adjustment grid  results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Adjustment with invalid date format")]
        public void AddAdjustmentWithInvalidDateFormat()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Adjustment with invalid date format", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 167
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 168
testRunner.And("Smith clicked on the Add Adjustment Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentMode",
                            "AdjCycleStartDate",
                            "AdjCycleEndtDate",
                            "InvestmentBanker",
                            "AdjustmentCode",
                            "Amount",
                            "Note"});
                table18.AddRow(new string[] {
                            "Dynamic",
                            "Dat2344-20",
                            "02-28-Datew",
                            "Andersen, Autumn",
                            "GRID",
                            "faker_amount",
                            "faker_note"});
#line 169
testRunner.And("Smith entered the folllowng Add Adjustment details", ((string)(null)), table18, "And ");
#line hidden
#line 172
testRunner.When("[Smith clicks on save button On Adjstment add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 173
testRunner.Then("[Smith should see an error message indicating invalid date format]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with all valid inputs")]
        [NUnit.Framework.CategoryAttribute("AddAdustmentcode:")]
        public void SuccessfullyAddANewAdjustmentCodeWithAllValidInputs()
        {
            string[] tagsOfScenario = new string[] {
                    "AddAdustmentcode:"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with all valid inputs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 181
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 182
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 183
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 184
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 185
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table19.AddRow(new string[] {
                            "faker_code",
                            "faker_descrip",
                            "faker_amount",
                            "faker_category",
                            "faker_glcode",
                            "faker_cost"});
#line 186
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table19, "And ");
#line hidden
#line 189
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 190
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("add a new Adjustment Code with duplicate Adjustment Code")]
        public void AddANewAdjustmentCodeWithDuplicateAdjustmentCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("add a new Adjustment Code with duplicate Adjustment Code", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 192
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 193
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 194
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 195
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 196
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table20.AddRow(new string[] {
                            "CA",
                            "faker_descrip",
                            "faker_amount",
                            "faker_category",
                            "faker_glcode",
                            "faker_cost"});
#line 197
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table20, "And ");
#line hidden
#line 200
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 201
testRunner.Then("display a popup indicicating Adjustment Code a duplicate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Attempt to add a new Adjustment Code with missing required inputs")]
        public void AttemptToAddANewAdjustmentCodeWithMissingRequiredInputs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Attempt to add a new Adjustment Code with missing required inputs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 203
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 204
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 205
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 206
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 207
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table21.AddRow(new string[] {
                            "",
                            "faker_descrip",
                            "faker_amount",
                            "faker_category",
                            "faker_glcode",
                            "faker_cost"});
#line 208
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table21, "And ");
#line hidden
#line 212
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 213
testRunner.Then("the system displays an error message indicating that Adstment code  field is requ" +
                        "ired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with Required fields only")]
        public void SuccessfullyAddANewAdjustmentCodeWithRequiredFieldsOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with Required fields only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 217
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 218
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 219
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 220
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 221
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table22.AddRow(new string[] {
                            "faker_code",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 222
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table22, "And ");
#line hidden
#line 225
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 226
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Attempt to add a new Adjustment Code with AdjustmentCode and AdjustmentDescriptio" +
            "n only")]
        public void AttemptToAddANewAdjustmentCodeWithAdjustmentCodeAndAdjustmentDescriptionOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Attempt to add a new Adjustment Code with AdjustmentCode and AdjustmentDescriptio" +
                    "n only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 228
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 229
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 230
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 231
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 232
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table23.AddRow(new string[] {
                            "faker_code",
                            "faker_descrip",
                            "",
                            "",
                            "",
                            ""});
#line 233
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table23, "And ");
#line hidden
#line 237
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 238
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with  AdjustmentCode and Amount only")]
        public void SuccessfullyAddANewAdjustmentCodeWithAdjustmentCodeAndAmountOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with  AdjustmentCode and Amount only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 240
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 241
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 242
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 243
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 244
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table24.AddRow(new string[] {
                            "faker_code",
                            "",
                            "faker_amount",
                            "",
                            "",
                            ""});
#line 245
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table24, "And ");
#line hidden
#line 248
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 249
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with  AdjustmentCode and Category only")]
        public void SuccessfullyAddANewAdjustmentCodeWithAdjustmentCodeAndCategoryOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with  AdjustmentCode and Category only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 251
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 252
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 253
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 254
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 255
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table25.AddRow(new string[] {
                            "faker_code",
                            "",
                            "",
                            "faker_category",
                            "",
                            ""});
#line 256
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table25, "And ");
#line hidden
#line 259
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 260
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with  AdjustmentCode and GL Code only")]
        public void SuccessfullyAddANewAdjustmentCodeWithAdjustmentCodeAndGLCodeOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with  AdjustmentCode and GL Code only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 262
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 263
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 264
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 265
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 266
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table26.AddRow(new string[] {
                            "faker_code",
                            "",
                            "",
                            "",
                            "faker_glcode",
                            ""});
#line 267
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table26, "And ");
#line hidden
#line 270
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 271
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully add a new Adjustment Code with  AdjustmentCode and Cost Center only")]
        public void SuccessfullyAddANewAdjustmentCodeWithAdjustmentCodeAndCostCenterOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully add a new Adjustment Code with  AdjustmentCode and Cost Center only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 273
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 274
testRunner.And("the user clicks the \"Adjustment Codes\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 275
testRunner.When("the Adjustment Code popup screen appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 276
testRunner.And("the user clicks the \"Add New\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 277
testRunner.Then("the \"Add Adjustment Code\" popup appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "AdjustmentCode",
                            "AdjustmentDescription",
                            "Amount",
                            "Category",
                            "GLCode",
                            "CostCenter"});
                table27.AddRow(new string[] {
                            "faker_code",
                            "",
                            "",
                            "",
                            "",
                            "faker_cost"});
#line 278
testRunner.And("the user enters the following valid inputs:", ((string)(null)), table27, "And ");
#line hidden
#line 281
testRunner.And("clicks \"Save\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 282
testRunner.Then("the new Adjustment Code is added to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
