// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace InvestmentBankingAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Deals")]
    public partial class DealsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Deals.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Deals", "-Deal search\r\n-add Deal\r\n-Receive revenue\r\n-Deal records\r\n--Deal retainer", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
#line 8
testRunner.Given("Smith has launched the intrepid application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserNameField",
                        "PasswordField"});
            table33.AddRow(new string[] {
                        "NewUserTest",
                        "P@ssword12"});
#line 9
 testRunner.And("Smith entered the following login details", ((string)(null)), table33, "And ");
#line hidden
#line 13
 testRunner.And("Smith clicked login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And("smith clicked on the Deals Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Type ,Deal Status ,Industry,Investment Banker")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealTypeDealStatusIndustryInvestmentBanker()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Type ,Deal Status ,Industry,Investment Banker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table34.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "Restaurant Group",
                            "Allen, Latasha"});
#line 18
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table34, "And ");
#line hidden
#line 21
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal with no filter")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealWithNoFilter()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal with no filter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table35.AddRow(new string[] {
                            "",
                            "",
                            "",
                            ""});
#line 26
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table35, "And ");
#line hidden
#line 29
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Type and Deal Status Only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealTypeAndDealStatusOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Type and Deal Status Only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table36.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "",
                            ""});
#line 34
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table36, "And ");
#line hidden
#line 38
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Type and Industry only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealTypeAndIndustryOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Type and Industry only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table37.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "",
                            "Restaurant Group",
                            ""});
#line 46
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table37, "And ");
#line hidden
#line 50
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Type and Investment Banker only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealTypeAndInvestmentBankerOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Type and Investment Banker only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table38.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "",
                            "",
                            "Allen, Latasha"});
#line 58
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table38, "And ");
#line hidden
#line 61
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Status and Industry only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealStatusAndIndustryOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Status and Industry only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table39.AddRow(new string[] {
                            "",
                            "Open",
                            "Restaurant Group",
                            ""});
#line 67
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table39, "And ");
#line hidden
#line 70
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Deal Status and Investment Banker only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByDealStatusAndInvestmentBankerOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Deal Status and Investment Banker only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table40.AddRow(new string[] {
                            "",
                            "Open",
                            "",
                            "Allen, Latasha"});
#line 76
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table40, "And ");
#line hidden
#line 79
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Deal by Industry and Investment Banker only")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchDealByIndustryAndInvestmentBankerOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Deal by Industry and Investment Banker only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "Industry",
                            "InvestmentBanker"});
                table41.AddRow(new string[] {
                            "",
                            "",
                            "Restaurant Group",
                            "Allen, Latasha"});
#line 86
 testRunner.And("Smith entered the following Search deal details", ((string)(null)), table41, "And ");
#line hidden
#line 89
 testRunner.When("[Smith cliks Search]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 90
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal add all fields without investment banker and revenuue")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealAddAllFieldsWithoutInvestmentBankerAndRevenuue()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal add all fields without investment banker and revenuue", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 94
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table42.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "Restaurant Group",
                            "faker_Address",
                            "faker_PhoneNumber",
                            "faker_OriginationDate"});
#line 95
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table42, "And ");
#line hidden
#line 98
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal with Required fields Only")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithRequiredFieldsOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal with Required fields Only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 107
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table43.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 108
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table43, "And ");
#line hidden
#line 111
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal without Deal type")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithoutDealType()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal without Deal type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 117
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table44.AddRow(new string[] {
                            "",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 118
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table44, "And ");
#line hidden
#line 121
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 122
 testRunner.Then("Smith should see a popup which says deal type is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal without Deal status")]
        public void AddDealWithoutDealStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal without Deal status", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 124
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 125
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table45.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "",
                            "faker_ClientName",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 126
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table45, "And ");
#line hidden
#line 129
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 130
 testRunner.Then("Smith should see a popup which says deal Status is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal without Client Name")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithoutClientName()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal without Client Name", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 134
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table46.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 135
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table46, "And ");
#line hidden
#line 138
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 139
 testRunner.Then("Smith should see a popup which says client name is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal with invalid origination Date")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithInvalidOriginationDate()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal with invalid origination Date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 144
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table47.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "Restaurant Group",
                            "faker_Address",
                            "faker_PhoneNumber",
                            "Dat2344-20"});
#line 145
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table47, "And ");
#line hidden
#line 149
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 150
 testRunner.Then("Smith should see an error which origination dates are invalid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal add all fields Including investment banker and retainers")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealAddAllFieldsIncludingInvestmentBankerAndRetainers()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal add all fields Including investment banker and retainers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 154
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 155
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table48.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "Restaurant Group",
                            "faker_Address",
                            "faker_PhoneNumber",
                            "faker_OriginationDate"});
#line 156
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table48, "And ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "InvestmentBanker",
                            "OriginationPercentage",
                            "StandardPayout",
                            "CapAmount"});
                table49.AddRow(new string[] {
                            "Allen, Latasha",
                            "faker_OriginationPercentage",
                            "faker_StandardPayout",
                            "faker_CapAmount"});
#line 159
 testRunner.And("Smith entered the folllowng Deal-investment Banker  details", ((string)(null)), table49, "And ");
#line hidden
#line 162
 testRunner.When("[Smith clicks on save Investment banker  button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
 testRunner.Then("[Smith should see the Added investment bannker  grid results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 164
 testRunner.When("smith clicks on the retainer tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                            "RevenueType",
                            "RevenueSource",
                            "CheckWireNumber",
                            "Amount",
                            "SettlementDate"});
                table50.AddRow(new string[] {
                            "Engagement Fee",
                            "Check",
                            "faker_CheckWireNumber",
                            "faker_Amount",
                            "faker_SettlementDate"});
#line 165
 testRunner.And("Smith entered the folllowng Deal-Revenue details", ((string)(null)), table50, "And ");
#line hidden
#line 168
 testRunner.When("[Smith clicks on save Retainer  button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 169
 testRunner.Then("[Smith should see the Added Revenue  grid results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 170
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 171
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal with  investment banker Without revenue")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithInvestmentBankerWithoutRevenue()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal with  investment banker Without revenue", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 176
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 177
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table51.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "Restaurant Group",
                            "faker_Address",
                            "faker_PhoneNumber",
                            "faker_OriginationDate"});
#line 178
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table51, "And ");
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "InvestmentBanker",
                            "OriginationPercentage",
                            "StandardPayout",
                            "CapAmount"});
                table52.AddRow(new string[] {
                            "Abbott, Steven",
                            "faker_OriginationPercentage",
                            "faker_StandardPayout",
                            "faker_CapAmount"});
#line 181
 testRunner.And("Smith entered the folllowng Deal-investment Banker  details", ((string)(null)), table52, "And ");
#line hidden
#line 184
 testRunner.When("[Smith clicks on save Investment banker  button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 185
 testRunner.Then("[Smith should see the Added investment bannker  grid results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 187
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 188
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Deal With  Revenue , without investment banker")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddDealWithRevenueWithoutInvestmentBanker()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Deal With  Revenue , without investment banker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 193
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 194
testRunner.And("Smith clicked on the Add Deal Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                            "DealType",
                            "DealStatus",
                            "ClientName",
                            "ActualDealAmount",
                            "ActuaCommissionRate",
                            "Industry",
                            "Address",
                            "PhoneNumber",
                            "OriginationDate"});
                table53.AddRow(new string[] {
                            "Mergers & Acquisitions – Sell Side",
                            "Open",
                            "faker_ClientName",
                            "",
                            "",
                            "Restaurant Group",
                            "faker_Address",
                            "faker_PhoneNumber",
                            "faker_OriginationDate"});
#line 195
testRunner.And("Smith entered the folllowng Add deal details", ((string)(null)), table53, "And ");
#line hidden
#line 198
 testRunner.When("smith clicks on the retainer tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "RevenueType",
                            "RevenueSource",
                            "CheckWireNumber",
                            "Amount",
                            "SettlementDate"});
                table54.AddRow(new string[] {
                            "Engagement Fee",
                            "Check",
                            "faker_CheckWireNumber",
                            "faker_Amount",
                            "faker_SettlementDate"});
#line 199
testRunner.And("Smith entered the folllowng Deal-Revenue details", ((string)(null)), table54, "And ");
#line hidden
#line 202
 testRunner.When("[Smith clicks on save Retainer  button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 203
 testRunner.Then("[Smith should see the Added Revenue  grid results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 205
 testRunner.When("[Smith clicks on save button On Deals add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 206
 testRunner.Then("[Smith should see the search deal grid has records]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
