// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace InvestmentBankingAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("InvestentBanker")]
    public partial class InvestentBankerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "InvestmentBanker.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "InvestentBanker", "-InvestentBanker search\r\n-add InvestentBanker", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
testRunner.Given("Smith has launched the intrepid application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserNameField",
                        "PasswordField"});
            table56.AddRow(new string[] {
                        "NewUserTest",
                        "P@ssword12"});
#line 7
 testRunner.And("Smith entered the following login details", ((string)(null)), table56, "And ");
#line hidden
#line 11
 testRunner.And("Smith clicked login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And("smith clicked on the InvestentBanker Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search InvestentBanker by IBanker Role ,IBanker Status ,Lname,Fname,SSN")]
        [NUnit.Framework.CategoryAttribute("Search")]
        public void SearchInvestentBankerByIBankerRoleIBankerStatusLnameFnameSSN()
        {
            string[] tagsOfScenario = new string[] {
                    "Search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search InvestentBanker by IBanker Role ,IBanker Status ,Lname,Fname,SSN", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table57.AddRow(new string[] {
                            "Vice President",
                            "Beahan",
                            "Smith",
                            "45788",
                            "Active"});
#line 16
 testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table57, "And ");
#line hidden
#line 19
 testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
 testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role only")]
        public void SearchInvestmentBankerByIBankerRoleOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table58.AddRow(new string[] {
                            "Vice President",
                            "",
                            "",
                            "",
                            ""});
#line 23
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table58, "And ");
#line hidden
#line 26
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Status only")]
        public void SearchInvestmentBankerByIBankerStatusOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Status only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table59.AddRow(new string[] {
                            "",
                            "",
                            "",
                            "",
                            "Active"});
#line 30
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table59, "And ");
#line hidden
#line 33
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Last Name only")]
        public void SearchInvestmentBankerByIBankerLastNameOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Last Name only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table60.AddRow(new string[] {
                            "",
                            "Beahan",
                            "",
                            "",
                            ""});
#line 37
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table60, "And ");
#line hidden
#line 40
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker SSN only")]
        public void SearchInvestmentBankerByIBankerSSNOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker SSN only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table61.AddRow(new string[] {
                            "",
                            "",
                            "",
                            "45788",
                            ""});
#line 45
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table61, "And ");
#line hidden
#line 48
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role and IBStatus")]
        public void SearchInvestmentBankerByIBankerRoleAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table62.AddRow(new string[] {
                            "Vice President",
                            "",
                            "",
                            "",
                            "Active"});
#line 52
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table62, "And ");
#line hidden
#line 55
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBFirstName and IBLastName")]
        public void SearchInvestmentBankerByIBFirstNameAndIBLastName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBFirstName and IBLastName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table63.AddRow(new string[] {
                            "",
                            "Beahan",
                            "Smith",
                            "",
                            ""});
#line 59
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table63, "And ");
#line hidden
#line 62
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 63
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role, IBLastName and IBSSN")]
        public void SearchInvestmentBankerByIBankerRoleIBLastNameAndIBSSN()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role, IBLastName and IBSSN", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table64.AddRow(new string[] {
                            "Vice President",
                            "Beahan",
                            "",
                            "45788",
                            ""});
#line 66
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table64, "And ");
#line hidden
#line 69
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 70
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBFirstName, IBLastName and IBStatus")]
        public void SearchInvestmentBankerByIBFirstNameIBLastNameAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBFirstName, IBLastName and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table65.AddRow(new string[] {
                            "",
                            "Beahan",
                            "Smith",
                            "",
                            "Active"});
#line 73
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table65, "And ");
#line hidden
#line 76
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 77
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role, IBFirstName and IBStatus")]
        public void SearchInvestmentBankerByIBankerRoleIBFirstNameAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role, IBFirstName and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table66.AddRow(new string[] {
                            "Vice President",
                            "",
                            "Smith",
                            "",
                            "Active"});
#line 80
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table66, "And ");
#line hidden
#line 83
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 84
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role, IBLastName and IBStatus")]
        public void SearchInvestmentBankerByIBankerRoleIBLastNameAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role, IBLastName and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table67.AddRow(new string[] {
                            "Vice President",
                            "Beahan",
                            "",
                            "",
                            "Active"});
#line 88
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table67, "And ");
#line hidden
#line 91
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 92
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBFirstName, IBSSN and IBStatus")]
        public void SearchInvestmentBankerByIBFirstNameIBSSNAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBFirstName, IBSSN and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table68.AddRow(new string[] {
                            "",
                            "",
                            "Smith",
                            "45788",
                            "Active"});
#line 95
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table68, "And ");
#line hidden
#line 98
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBLastName, IBSSN and IBStatus")]
        public void SearchInvestmentBankerByIBLastNameIBSSNAndIBStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBLastName, IBSSN and IBStatus", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table69.AddRow(new string[] {
                            "",
                            "Beahan",
                            "",
                            "45788",
                            "Active"});
#line 102
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table69, "And ");
#line hidden
#line 105
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 106
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Investment Banker by IBanker Role, IBFirstName, IBLastName and IBSSN")]
        public void SearchInvestmentBankerByIBankerRoleIBFirstNameIBLastNameAndIBSSN()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Investment Banker by IBanker Role, IBFirstName, IBLastName and IBSSN", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 108
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBRole",
                            "IBLastName",
                            "IBFirstName",
                            "IBSSN",
                            "IBStatus"});
                table70.AddRow(new string[] {
                            "Vice President",
                            "Beahan",
                            "Smith",
                            "45788",
                            ""});
#line 109
testRunner.And("Smith entered the following Search Investment Banker details", ((string)(null)), table70, "And ");
#line hidden
#line 112
testRunner.When("[Smith cliks Search on Investment banker]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 113
testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add all fields on Investment Banker")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddAllFieldsOnInvestmentBanker()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add all fields on Investment Banker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 123
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table71.AddRow(new string[] {
                            "Active",
                            "faker_LastName",
                            "faker_Email",
                            "Vice President",
                            "faker_FirstName",
                            "faker_MiddleName",
                            "faker_NickName",
                            "faker_DOB",
                            "faker_HireDate",
                            "faker_TerminatedDate",
                            "faker_EmployeeNum",
                            "faker_HomePhone",
                            "faker_WorkPhone",
                            "faker_Fax",
                            "faker_CellNmber",
                            "faker_Address",
                            "faker_SSN",
                            "faker_City",
                            "faker_State",
                            "faker_ZIP",
                            "Andersen, Autumn"});
#line 124
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table71, "And ");
#line hidden
#line 127
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 128
  testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Investment Banker with invalid Email")]
        [NUnit.Framework.CategoryAttribute("Add")]
        public void AddInvestmentBankerWithInvalidEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "Add"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Investment Banker with invalid Email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 132
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 133
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table72.AddRow(new string[] {
                            "Active",
                            "faker_LastName",
                            "@ggmail.com",
                            "Vice President",
                            "faker_FirstName",
                            "faker_MiddleName",
                            "faker_NickName",
                            "faker_DOB",
                            "faker_HireDate",
                            "faker_TerminatedDate",
                            "faker_EmployeeNum",
                            "faker_HomePhone",
                            "faker_WorkPhone",
                            "faker_Fax",
                            "faker_CellNmber",
                            "faker_Address",
                            "faker_SSN",
                            "faker_City",
                            "faker_State",
                            "faker_ZIP",
                            "Andersen, Autumn"});
#line 134
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table72, "And ");
#line hidden
#line 137
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 138
  testRunner.Then("Smith should see an error message indicating that the email address is invalid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Investment Banker without Lastname")]
        public void AddInvestmentBankerWithoutLastname()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Investment Banker without Lastname", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 140
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 141
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table73.AddRow(new string[] {
                            "Active",
                            "",
                            "faker_Email",
                            "Vice President",
                            "faker_FirstName",
                            "faker_MiddleName",
                            "faker_NickName",
                            "faker_DOB",
                            "faker_HireDate",
                            "faker_TerminatedDate",
                            "faker_EmployeeNum",
                            "faker_HomePhone",
                            "faker_WorkPhone",
                            "faker_Fax",
                            "faker_CellNmber",
                            "faker_Address",
                            "faker_SSN",
                            "faker_City",
                            "faker_State",
                            "faker_ZIP",
                            "Andersen, Autumn"});
#line 142
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table73, "And ");
#line hidden
#line 145
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 146
  testRunner.Then("Smith should see an error message indicating that the Lastname is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Investment Banker without status")]
        public void AddInvestmentBankerWithoutStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Investment Banker without status", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 148
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 149
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table74.AddRow(new string[] {
                            "",
                            "faker_LastName",
                            "faker_Email",
                            "Vice President",
                            "faker_FirstName",
                            "faker_MiddleName",
                            "faker_NickName",
                            "faker_DOB",
                            "faker_HireDate",
                            "faker_TerminatedDate",
                            "faker_EmployeeNum",
                            "faker_HomePhone",
                            "faker_WorkPhone",
                            "faker_Fax",
                            "faker_CellNmber",
                            "faker_Address",
                            "faker_SSN",
                            "faker_City",
                            "faker_State",
                            "faker_ZIP",
                            "Andersen, Autumn"});
#line 150
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table74, "And ");
#line hidden
#line 153
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 154
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 155
  testRunner.Then("Smith should see an error message indicating that status is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Required fields only on Investment Banker")]
        public void AddRequiredFieldsOnlyOnInvestmentBanker()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Required fields only on Investment Banker", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 157
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 158
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table75.AddRow(new string[] {
                            "Active",
                            "faker_LastName",
                            "faker_Email",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "faker_ZIP",
                            ""});
#line 159
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table75, "And ");
#line hidden
#line 162
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
  testRunner.Then("[Smith should see investment banker grid search results]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Investment Banker with Invalid :Date of birth,Hiredate,Teminated date")]
        public void AddInvestmentBankerWithInvalidDateOfBirthHiredateTeminatedDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Investment Banker with Invalid :Date of birth,Hiredate,Teminated date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 165
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 166
testRunner.And("Smith clicked on the Add InvestmentBanker Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                            "IBStatus",
                            "IBLastName",
                            "IBEmail",
                            "IBrole",
                            "IBFname",
                            "IBMiddleName",
                            "IBNickName",
                            "IBDOB",
                            "IBHireDate",
                            "IBTerminatedDate",
                            "IBEmployeeNum",
                            "IBHomePhone",
                            "IBWorkPhone",
                            "IBFax",
                            "IBCellNumber",
                            "IBAddress",
                            "IBSSN",
                            "IBCity",
                            "IBState",
                            "IBZip",
                            "Supervisor"});
                table76.AddRow(new string[] {
                            "Active",
                            "faker_LastName",
                            "23568@ggmail.com",
                            "Vice President",
                            "faker_FirstName",
                            "faker_MiddleName",
                            "faker_NickName",
                            "233/533/2333",
                            "233/533/2333",
                            "233/533/2333",
                            "faker_EmployeeNum",
                            "faker_HomePhone",
                            "faker_WorkPhone",
                            "faker_Fax",
                            "faker_CellNmber",
                            "faker_Address",
                            "faker_SSN",
                            "faker_City",
                            "faker_State",
                            "faker_ZIP",
                            "Andersen, Autumn"});
#line 167
testRunner.And("Smith entered the folllowng Add InvestmentBanker details", ((string)(null)), table76, "And ");
#line hidden
#line 171
 testRunner.When("[Smith clicks on the save button ON InvesmentBanker add screen]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 172
  testRunner.Then("Smith should see an error message indicating that the dates are invalid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
