// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace InvestmentBankingAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReportManager")]
    public partial class ReportManagerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ReportManager.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "ReportManager", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
testRunner.Given("Smith has launched the intrepid application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserNameField",
                        "PasswordField"});
            table80.AddRow(new string[] {
                        "NewUserTest",
                        "P@ssword12"});
#line 7
 testRunner.And("Smith entered the following login details", ((string)(null)), table80, "And ");
#line hidden
#line 11
 testRunner.And("Smith clicked login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And("Smith has navigated to the Report Manager page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate a Banker Monthly Statement report")]
        [NUnit.Framework.CategoryAttribute("COMMISSION")]
        [NUnit.Framework.CategoryAttribute("BankerMonthlyStatement")]
        [NUnit.Framework.TestCaseAttribute("May 2023 (Open)", "Allen, Latasha []", "COMMISSION", "Banker Monthly Statement", null)]
        [NUnit.Framework.TestCaseAttribute("Apr 2023 (Closed)", "Barnes, Eugene []", "COMMISSION", "Banker Monthly Statement", null)]
        [NUnit.Framework.TestCaseAttribute("Mar 2023 (Closed)", "Edwards, Wendy []", "COMMISSION", "Banker Monthly Statement", null)]
        [NUnit.Framework.TestCaseAttribute("Feb 2023 (Closed)", "Abbott, Steven []", "COMMISSION", "Banker Monthly Statement", null)]
        [NUnit.Framework.TestCaseAttribute("Jan 2023 (Closed)", "Acevedo, Damien []", "COMMISSION", "Banker Monthly Statement", null)]
        public void GenerateABankerMonthlyStatementReport(string cycleDate, string bankerList, string reportGroup, string reportType, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "COMMISSION",
                    "BankerMonthlyStatement"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CycleDate", cycleDate);
            argumentsOfScenario.Add("bankerList", bankerList);
            argumentsOfScenario.Add("ReportGroup", reportGroup);
            argumentsOfScenario.Add("ReportType", reportType);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate a Banker Monthly Statement report", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 18
testRunner.Given("Smith is on the Report Manager page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
testRunner.When(string.Format("Smith selects the \"{0}\" report folder", reportGroup), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
  testRunner.And(string.Format("Smith clicks on the \"{0}\" report link", reportType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
testRunner.And(string.Format("Smith enters the following criteria on BankerMonthlyStatement report:\"{0}\" \"{1}\"", cycleDate, bankerList), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
testRunner.And("Smith clicks on the Run report button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
testRunner.Then("the report should load and display I22 Investment Banking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
